title:              Balaram Bhattarai
email:              dhiraj.ipcamp@gmail.com
description:        An Advocate and a Campaigner
author:             B R Bhattarai
baseurl:            ""
url:                "https://brbhattarai.github.io"

# Social Profiles
twitter_username:   # SBootstrap
github_username:   # StartBootstrap
facebook_username:  balaram.bhattarai
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
